version: '3'

services:
  web:
    build: .
    ports:
      - "3003:3000"
      - "3004:3001"
    environment:
      - SOCKET_PORT=3001
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL:-}
    volumes:
      - ./prisma:/app/prisma
      - ./scripts:/app/scripts
    networks:
      - app_network
    command: ["sh", "./scripts/migrate.sh", "node", "server.js"]

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: 