version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # Not exposing ports directly to the host - Nginx will handle this
    expose:
      - "3000"
    networks:
      - app_network
      - nginx_network
    volumes:
      - ./prisma:/app/prisma
      - db_data:/app/prisma/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/data/prod.db
      # Set to placeholder hostname (will be handled by Nginx)
      - HOSTNAME="0.0.0.0"
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run start
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      - "traefik.enable=true"
      - "app=ape-oracle"

networks:
  app_network:
    driver: bridge
  nginx_network:
    external: true  # Assumes you already have an nginx network created

volumes:
  db_data:
    driver: local 