version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - SOCKET_PORT=3001
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL:-}
    depends_on:
      - database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: 