version: '3'

services:
  web:
    build: .
    ports:
      - "3003:3000"
      - "3004:3001"
    environment:
      - SOCKET_PORT=3001
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL:-}
    volumes:
      - sqlite_data:/app/prisma
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  sqlite_data:
  postgres_data: 